(test
 (name test_btc)
 (modules Test_btc)
 (package ledgerwallet-btc)
 (libraries alcotest-lwt ledgerwallet-btc))

(test
 (name test_mavryk)
 (modules Test_mavryk)
 (package ledgerwallet-mavryk)
 (libraries alcotest-lwt ledgerwallet-mavryk secp256k1 uecc))

(test
 (name test_zil)
 (modules Test_zil)
 (package ledgerwallet-zil)
 (libraries hex alcotest-lwt ledgerwallet-zil))

(test
 (name test_ssh_agent)
 (modules Test_ssh_agent)
 (package ledgerwallet-ssh-agent)
 (libraries hex alcotest-lwt ledgerwallet-ssh-agent))
